# Checkov Configuration for AKS Terraform Project

directory:
  - modules/
  - envs/

framework:
  - terraform

skip-path:
  - .terraform/
  - .git/
  - scripts/

skip-check: []

soft-fail: false
compact: true
quiet: false

output:
  - cli
  - junitxml

# Removed: enable-secret-scan: true
# Secret scanning is enabled by default in recent Checkov versions

download-external-modules: true
parallel: true
